### ISSUE TITLE
Adapter no longer compatible

### ISSUE THREAD

**Issue by ia3n** [Vintar/Xamarin.Android.GoogleAdsMediation.FacebookAdapter#2]
This adapter is fantastic but no longer works with the latest admob nugets for mediation. Also for new features like open bidding a more recent .aar has to be used, and facebook have implemented a rule that the adapter version must now match the admob version (e.g. the .aar of v6.1.0 must be used with google play ads 6.1.0).
Any chance of an updated version? I tried making my own binding with the latest facebook adapter but don't have the knowledge to get it to work.

**Comment by Vintar** [comment]
Check out the nuget. A week ago I updated the adapters and sdk for: Facebook, UnityAds, AdColony and AppLovin to the latest versions.

**Comment by ia3n** [comment]
Yes, already implemented and working beautifully. Love your work, thank you!!

**Comment by Vintar** [comment]
![image](https://user-images.githubusercontent.com/15018771/123439176-c088bd00-d5d1-11eb-83a6-91ff304641ca.png)
